startWebURI: /bin/cms.cgi/system/content/webtop/
maxScriptCachePerScriptEngine: 32
nativeEcmaPoolSizePerScriptEngine: 0
classLoaderRefreshInterval: 3

security:
  serviceAccounts:
    - name: cms-batch-user
      description: "Service account for batch processing"
      groups:
        - batch-service-group

