security:
    serviceCredentials:
      - org.mintjams.rt.cms.internal.security.CmsServiceCredentials
      - org.mintjams.idp.internal.security.IdpServiceCredentials
    principalProviders:
      - org.mintjams.rt.cms.internal.security.auth.saml2.Saml2PrincipalProvider
      - org.mintjams.rt.cms.internal.security.DefaultPrincipalProvider
      - org.mintjams.rt.cms.internal.security.ServiceAccountPrincipalProvider
    identityProviders:
      - org.mintjams.rt.cms.internal.security.DefaultIdentityProvider
