source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               lib/,\
               lib/accessors-smart-2.6.0.jar,\
               lib/asm-9.7.1.jar,\
               lib/camel-api-4.18.1.jar,\
               lib/camel-base-4.18.1.jar,\
               lib/camel-base-engine-4.18.1.jar,\
               lib/camel-bean-4.18.1.jar,\
               lib/camel-cluster-4.18.1.jar,\
               lib/camel-core-engine-4.18.1.jar,\
               lib/camel-core-languages-4.18.1.jar,\
               lib/camel-core-model-4.18.1.jar,\
               lib/camel-core-processor-4.18.1.jar,\
               lib/camel-core-reifier-4.18.1.jar,\
               lib/camel-direct-4.18.1.jar,\
               lib/camel-dsl-support-4.18.1.jar,\
               lib/camel-file-4.18.1.jar,\
               lib/camel-jsonpath-4.18.1.jar,\
               lib/camel-management-api-4.18.1.jar,\
               lib/camel-seda-4.18.1.jar,\
               lib/camel-support-4.18.1.jar,\
               lib/camel-timer-4.18.1.jar,\
               lib/camel-util-4.18.1.jar,\
               lib/camel-util-json-4.18.1.jar,\
               lib/camel-xml-io-4.18.1.jar,\
               lib/camel-xml-io-dsl-4.18.1.jar,\
               lib/camel-xml-io-util-4.18.1.jar,\
               lib/camel-xml-jaxp-4.18.1.jar,\
               lib/camel-xml-jaxp-util-4.18.1.jar,\
               lib/camel-xpath-4.18.1.jar,\
               lib/camel-xslt-4.18.1.jar,\
               lib/jackson-annotations-2.19.4.jar,\
               lib/jackson-core-2.19.4.jar,\
               lib/jackson-databind-2.19.4.jar,\
               lib/jakarta.activation-api-2.1.4.jar,\
               lib/jakarta.xml.bind-api-4.0.5.jar,\
               lib/json-path-2.10.0.jar,\
               lib/json-smart-2.6.0.jar,\
               lib/slf4j-api-2.0.17.jar
