source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               lib/,\
               lib/graphql-java-22.3.jar,\
               lib/java-dataloader-3.3.0.jar,\
               lib/reactive-streams-1.0.3.jar
