CREATE TABLE IF NOT EXISTS jcr_cluster_nodes (
	node_id VARCHAR NOT NULL,
	host_name VARCHAR,
	node_started BIGINT NOT NULL,
	last_heartbeat BIGINT NOT NULL,
	PRIMARY KEY (node_id)
);

CREATE TABLE IF NOT EXISTS jcr_cluster_locks (
	lock_name VARCHAR NOT NULL,
	owner_id VARCHAR NOT NULL,
	lock_acquired BIGINT NOT NULL,
	lock_expires BIGINT NOT NULL,
	PRIMARY KEY (lock_name)
);

CREATE TABLE IF NOT EXISTS jcr_journal_commits (
	commit_seq BIGINT GENERATED BY DEFAULT AS IDENTITY,
	transaction_id VARCHAR NOT NULL,
	node_id VARCHAR NOT NULL,
	committed BIGINT NOT NULL,
	PRIMARY KEY (commit_seq)
);
CREATE INDEX IF NOT EXISTS jcr_journal_commits_index1 ON jcr_journal_commits (committed);

CREATE TABLE IF NOT EXISTS jcr_journal_offsets (
	node_id VARCHAR NOT NULL,
	consumed_seq BIGINT NOT NULL,
	updated BIGINT NOT NULL,
	PRIMARY KEY (node_id)
);

