/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mintjams_rt_cms_internal_script_engine_nativeecma_NativeEcma */

#ifndef _Included_org_mintjams_rt_cms_internal_script_engine_nativeecma_NativeEcma
#define _Included_org_mintjams_rt_cms_internal_script_engine_nativeecma_NativeEcma
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mintjams_rt_cms_internal_script_engine_nativeecma_NativeEcma
 * Method:    nativeInitPlatform
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_mintjams_rt_cms_internal_script_engine_nativeecma_NativeEcma_nativeInitPlatform
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_mintjams_rt_cms_internal_script_engine_nativeecma_NativeEcma
 * Method:    nativeCreatePool
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_mintjams_rt_cms_internal_script_engine_nativeecma_NativeEcma_nativeCreatePool
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_mintjams_rt_cms_internal_script_engine_nativeecma_NativeEcma
 * Method:    nativeDestroyPool
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_mintjams_rt_cms_internal_script_engine_nativeecma_NativeEcma_nativeDestroyPool
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_mintjams_rt_cms_internal_script_engine_nativeecma_NativeEcma
 * Method:    nativeEval
 * Signature: (J[Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_mintjams_rt_cms_internal_script_engine_nativeecma_NativeEcma_nativeEval
  (JNIEnv *, jobject, jlong, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
