identifier: 18c1c623-fc2d-4492-ba29-ae019c6c5264
title: EIP Modeler
icon: assets/icons/icon.svg
editor: true
contentTypes:
  - application/vnd.webtop.eip+xml
actions:
  open:
    icon: open
    label: Open
minimumWidth: 960
minimumHeight: 540
customWindowControls: true
