source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               OSGI-INF/,\
               .,\
               lib/,\
               lib/bcpkix-jdk18on-1.83.jar,\
               lib/bcprov-jdk18on-1.83.jar,\
               lib/bcutil-jdk18on-1.83.jar
